name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3



dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/welcomescreen/
      - assets/homescreen/
      - assets/icons/
      - assets/fonts/
      - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf



  
